name: Build with Cachix Installer

on:  
  workflow_dispatch:
    inputs:
      pkgs:
        description: 'Package to build'
        required: true
        default: 'github:daeuniverse/flake.nix#daed'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build
        run: |
          nix build ${{ github.event.inputs.pkgs }}
