name: Build with DetSys Installer

on:  
  workflow_dispatch:
    inputs:
      pkgs:
        description: 'Package to build'
        required: true
        default: 'github:daeuniverse/flake.nix#daed'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build
        run: |
          nix build ${{ github.event.inputs.pkgs }}
