name: Test update script from nix-gaming

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source
        uses: actions/checkout@v4
        with:
            repository: fufexan/nix-gaming

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Build
        run: |
          nix-build --no-out-link -A "packages.x86_64-linux.faf-client.mitmCache.updateScript"
