name: Test update script from nix-gaming

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source
        uses: actions/checkout@v4
        with:
            repository: fufexan/nix-gaming

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update npins
        run: nix run nixpkgs#npins update
      
      - run: pkgs/faf-client/update.sh
      - run: pkgs/faf-client/update-src.sh