name: Build with nixbuild Quick Installer and flake-compat

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source
        uses: actions/checkout@v4
        with:
            repository: ccicnce113424/nixos-config

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Build
        run: |
          nix-build --attr nixosConfigurations.livecd.config.system.build.isoImage
